# Cerberus Copyright (C) 2016 Cerberus Testing
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This file is part of Cerberus.
#
# Cerberus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cerberus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cerberus. If not, see <http://www.gnu.org/licenses/>.
# Cerberus Glassfish MySQL composition.

# Run a Cerberus instance with a Glassfish application server and a MySQL database.
# Run also a Selenium hub with two nodes with respectively the Mozilla Firefox and Google Chrome Web browsers.
#
# How to run:
#   - $ git clone https://github.com/cerberustesting/cerberus-docker.git
#   - $ cd cerberus-docker/compositions/cerberus-glassfish-mysql
#   - $ docker-compose up
#   - Waiting for images startup
#   - Open your favorite browser and go to <docker_host>:18080/Cerberus, where <docker_host> is your Docker host
#
# Exposed ports:
#   - 13306: MySQL database access
#   - 18080: Glassfish HTTP access
#   - 14848: Glassfsh administration console access
#   - 14444: The Selenium hub port
#
# Volumes:
#   - MySQL data directory                      : FROM /var/lib/mysql                                                             TO ../localdata/mysql-db      (SERVICE cerberus-db-mysql)
#   - Cerberus execution screenshots directory  : FROM /usr/local/glassfish4/glassfish/domains/domain1/docroot/CerberusPictures   TO ../localdata/screenshots   (SERVICE cerberus-as-glassfish)
#   - Cerberus server log directory             : FROM /usr/local/glassfish4/glassfish/domains/domain1/logs                       TO ../localdata/logs          (SERVICE cerberus-as-glassfish)
#     ** IMPORTANT **
#     The default mapping values are for test only. Don't forget to change them to be more relevant with your configuration.
version: '2'
services:
  # Cerebrus internal services
  cerberus-db-mysql:
    image: cerberustesting/cerberus-db-mysql:latest
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./localdata/mysql-db:/var/lib/mysql
  cerberus-as-glassfish:
    image: cerberustesting/cerberus-as-glassfish:latest
    environment:
      - DATABASE_HOST=cerberus-db-mysql
      - DATABASE_PORT=3306
    ports:
      - "18080:8080"
      - "14848:4848"
    volumes:
      - ./localdata/screenshots:/usr/local/glassfish4/glassfish/domains/domain1/docroot/CerberusPictures
      - ./localdata/logs:/usr/local/glassfish4/glassfish/domains/domain1/logs
    depends_on:
      - cerberus-db-mysql
    links:
      - cerberus-db-mysql

  # Selenium-related services
  selenium-hub:
    image: selenium/hub:2.53.0
    expose:
      - "4444"
    ports:
      - "14444:4444"
  selenium-node-firefox:
    image: selenium/node-firefox-debug:2.53.0
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
  selenium-node-chrome:
    image: selenium/node-chrome-debug:2.53.0
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
